theme: jekyll-theme-dinky
<div id="badges">
  <a href="www.linkedin.com/in/elena-arroyo-636b38333">
    <img src="https://img.shields.io/badge/LinkedIn-blue?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn Badge"/>
  </a>
</div>
